#!/usr/bin/env python3

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


DEFAULT_CSV = Path("tools/kpkd_response_test/logs/step_response.csv")

JOINT_NAMES = [
    "LF HipA", "LR HipA", "RF HipA", "RR HipA",
    "LF HipF", "LR HipF", "RF HipF", "RR HipF",
    "LF Knee", "LR Knee", "RF Knee", "RR Knee",
]


def main() -> int:
    parser = argparse.ArgumentParser(description="Plot 12-joint kp/kd step response CSV.")
    parser.add_argument("csv", nargs="?", type=Path, default=DEFAULT_CSV,
                        help=f"CSV generated by kpkd_response_test (default: {DEFAULT_CSV})")
    parser.add_argument("--output", "-o", type=Path, help="Output PNG path")
    parser.add_argument("--show", action="store_true", help="Show interactive plot")
    args = parser.parse_args()

    df = pd.read_csv(args.csv)
    if "time_s" not in df.columns:
        raise SystemExit("CSV missing time_s column")

    out = args.output
    if out is None:
        out = args.csv.with_suffix(".png")

    fig, axes = plt.subplots(3, 4, figsize=(16, 9), sharex=True)
    axes = axes.flatten()

    t = df["time_s"]
    for i, ax in enumerate(axes):
        pos_col = f"pos_j{i}"
        target_col = f"target_j{i}"
        if pos_col not in df.columns or target_col not in df.columns:
            raise SystemExit(f"CSV missing {pos_col} or {target_col}")

        ax.plot(t, df[target_col], "--", linewidth=1.2, label="target")
        ax.plot(t, df[pos_col], linewidth=1.4, label="feedback")
        ax.set_title(f"J{i} {JOINT_NAMES[i]}")
        ax.grid(True, alpha=0.3)
        ax.set_ylabel("rad")

    for ax in axes[-4:]:
        ax.set_xlabel("time [s]")
    axes[0].legend(loc="best")

    fig.suptitle(args.csv.name)
    fig.tight_layout()
    out.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out, dpi=160)
    print(f"Saved plot: {out}")

    if args.show:
        plt.show()

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
