#!/usr/bin/env python3

import argparse
import csv
from pathlib import Path

import torch


JOINT_ORDER = [
    "LF_HipA", "LR_HipA", "RF_HipA", "RR_HipA",
    "LF_HipF", "LR_HipF", "RF_HipF", "RR_HipF",
    "LF_Knee", "LR_Knee", "RF_Knee", "RR_Knee",
]


def parse_args():
    parser = argparse.ArgumentParser(
        description="Convert ARES chirp CSV logs into PACE chirp_data.pt format."
    )
    parser.add_argument("input_csv", type=Path, help="Path to CSV generated by collect_pace_data")
    parser.add_argument("output_pt", type=Path, help="Output path for chirp_data.pt")
    return parser.parse_args()


def load_csv(csv_path: Path):
    times = []
    des_rows = []
    meas_rows = []

    with csv_path.open("r", newline="") as f:
        reader = csv.DictReader(f)
        expected = [f"des_{name}" for name in JOINT_ORDER] + [f"meas_{name}" for name in JOINT_ORDER]
        missing = [key for key in ["time", *expected] if key not in reader.fieldnames]
        if missing:
            raise ValueError(f"missing CSV columns: {missing}")

        for row in reader:
            times.append(float(row["time"]))
            des_rows.append([float(row[f"des_{name}"]) for name in JOINT_ORDER])
            meas_rows.append([float(row[f"meas_{name}"]) for name in JOINT_ORDER])

    if not times:
        raise ValueError("CSV is empty")

    return (
        torch.tensor(times, dtype=torch.float32),
        torch.tensor(meas_rows, dtype=torch.float32),
        torch.tensor(des_rows, dtype=torch.float32),
    )


def main():
    args = parse_args()
    time_data, dof_pos, des_dof_pos = load_csv(args.input_csv)

    args.output_pt.parent.mkdir(parents=True, exist_ok=True)
    torch.save(
        {
            "time": time_data,
            "dof_pos": dof_pos,
            "des_dof_pos": des_dof_pos,
            "joint_order": JOINT_ORDER,
            "source_csv": str(args.input_csv),
        },
        args.output_pt,
    )

    print(f"Saved {args.output_pt}")
    print("Joint order:", JOINT_ORDER)


if __name__ == "__main__":
    main()
